-dontobfuscate
-dontwarn *
-keep class es.chiteroman.playintegrityfix.EntryPoint {public <methods>;}
-keep class es.chiteroman.playintegrityfix.CustomKeyStoreSpi
-keep class es.chiteroman.playintegrityfix.CustomProvider
-keep class es.chiteroman.playintegrityfix.CustomPackageInfoCreator
-keep class org.lsposed.hiddenapibypass.** { *; }
